overrides:
  defu: 6.1.7
  esbuild: 0.28.1
  postcss: 8.5.23
  nanoid: 3.3.18
  browserslist: 4.28.7
  "gray-matter>js-yaml": 3.15.2
  "remark-mdx-frontmatter>toml": 4.2.0
  uuid: 11.1.1

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
